/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIv2;
import java.awt.CardLayout;
/**
 *
 * @author shrey
 */
public class MainFrame extends javax.swing.JFrame {
    String prev="initPanel";
    /*
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    private void callInitFrame()
    {
        CardLayout cards=(CardLayout)mainPanel.getLayout();
        cards.show(mainPanel, "initPanel");
    }
    private void callSignInPanel()
    {
        err_signin_label.setVisible(false);
        CardLayout cards=(CardLayout)mainPanel.getLayout();
        cards.show(mainPanel, "signinPanel");
    }
    private void callRegisterPanel()
    {
        err_reg_label.setVisible(false);
        CardLayout cards=(CardLayout)mainPanel.getLayout();
        cards.show(mainPanel, "registerPanel");
    }
    private void callHomePanel()
    {
        username_label.setText(getUsername());
        wallet_status_label.setText(getWallet());
        int x=Integer.parseInt(getWallet());
        if(isInTrip())
        {
            home_book_button.setEnabled(false); 
            home_err_label.setText("Trip ongoing...");
            home_err_label.setVisible(true);
        }
        else if(x<=300)
        {
            home_book_button.setEnabled(false); 
            home_err_label.setText("Less Money in Wallet. Please Add Money...");
            home_err_label.setVisible(true);
        }
        else
        {
            home_book_button.setEnabled(true); 
            home_err_label.setVisible(false);            
        }
        CardLayout cards=(CardLayout)mainPanel.getLayout();
        cards.show(mainPanel, "homePanel");
    }
    private void callHomePanel(String msg)
    {
        username_label.setText(getUsername());
        wallet_status_label.setText(getWallet());
        int x=Integer.parseInt(getWallet());
        if(isInTrip())
        {
            home_book_button.setEnabled(false); 
            home_err_label.setText("Trip ongoing...");
            home_err_label.setVisible(true);
        }
        else if(x<=300)
        {
            home_book_button.setEnabled(false); 
            home_err_label.setText("Less Money in Wallet. Please Add Money...");
            home_err_label.setVisible(true);
        }
        else
        {
            home_book_button.setEnabled(true); 
            home_err_label.setText(msg);
            home_err_label.setVisible(true);            
        }
        CardLayout cards=(CardLayout)mainPanel.getLayout();
        cards.show(mainPanel, "homePanel");
    }
    private boolean isInTrip()
    {
        return false;
    }
    private String getUsername()
    {
        return "Shreyam";
    }
    private String getWallet()
    {
        return "600";
    }
    private boolean isRegValid()
    {
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        initPanel = new javax.swing.JPanel();
        ExistingUserButton = new javax.swing.JButton();
        NewUserButton = new javax.swing.JButton();
        signinPanel = new javax.swing.JPanel();
        user_field = new javax.swing.JTextField();
        user_label = new javax.swing.JLabel();
        pass_label = new javax.swing.JLabel();
        pass_field = new javax.swing.JPasswordField();
        signIn = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        err_signin_label = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        name_text = new javax.swing.JTextField();
        email_text = new javax.swing.JTextField();
        name_label = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        pass_reg_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pass_reg_field = new javax.swing.JPasswordField();
        retypepass_reg_field = new javax.swing.JPasswordField();
        reg_button = new javax.swing.JButton();
        reset_reg_button = new javax.swing.JButton();
        err_reg_label = new javax.swing.JLabel();
        errPanel = new javax.swing.JPanel();
        errLabel = new javax.swing.JLabel();
        prev_err_button = new javax.swing.JButton();
        homePanel = new javax.swing.JPanel();
        home_book_button = new javax.swing.JButton();
        add_home_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        username_label = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        wallet_status_label = new javax.swing.JTextField();
        home_err_label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        sign_out_menuitem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        ExistingUserButton.setText("Existing User");
        ExistingUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExistingUserButtonMouseClicked(evt);
            }
        });

        NewUserButton.setText("New User");
        NewUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout initPanelLayout = new javax.swing.GroupLayout(initPanel);
        initPanel.setLayout(initPanelLayout);
        initPanelLayout.setHorizontalGroup(
            initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initPanelLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ExistingUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        initPanelLayout.setVerticalGroup(
            initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(ExistingUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(NewUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        mainPanel.add(initPanel, "initPanel");

        user_label.setText("Username");

        pass_label.setText("Password");

        signIn.setText("Sign in");
        signIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInMouseClicked(evt);
            }
        });

        reset.setText("Reset");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });

        err_signin_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        err_signin_label.setText("ERROR");
        err_signin_label.setVisible(false);

        javax.swing.GroupLayout signinPanelLayout = new javax.swing.GroupLayout(signinPanel);
        signinPanel.setLayout(signinPanelLayout);
        signinPanelLayout.setHorizontalGroup(
            signinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinPanelLayout.createSequentialGroup()
                .addGroup(signinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signinPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(signinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_label)
                            .addComponent(pass_label))
                        .addGap(26, 26, 26)
                        .addGroup(signinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(user_field)
                            .addComponent(pass_field, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(signinPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signinPanelLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(err_signin_label, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        signinPanelLayout.setVerticalGroup(
            signinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(signinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(signinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass_field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(signinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(err_signin_label, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(signinPanel, "signinPanel");

        name_label.setText("Username");

        email_label.setText("Email");

        pass_reg_label.setText("Password");

        jLabel4.setText("Retype Password");

        reg_button.setText("Register");
        reg_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reg_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reg_buttonMouseEntered(evt);
            }
        });

        reset_reg_button.setText("Reset");
        reset_reg_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_reg_buttonMouseClicked(evt);
            }
        });

        err_reg_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        err_reg_label.setText("ERROR");
        err_reg_label.setVisible(false);

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(name_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addComponent(pass_reg_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(err_reg_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pass_reg_field)
                    .addComponent(name_text)
                    .addComponent(email_text)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addComponent(reg_button)
                        .addGap(18, 18, 18)
                        .addComponent(reset_reg_button)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(retypepass_reg_field))
                .addGap(156, 156, 156))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_label))
                .addGap(15, 15, 15)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_label)
                    .addComponent(email_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_reg_label)
                    .addComponent(pass_reg_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(retypepass_reg_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reg_button, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(reset_reg_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(err_reg_label)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        mainPanel.add(registerPanel, "registerPanel");

        errLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        errLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errLabel.setText("Error");

        prev_err_button.setText("Back");
        prev_err_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prev_err_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout errPanelLayout = new javax.swing.GroupLayout(errPanel);
        errPanel.setLayout(errPanelLayout);
        errPanelLayout.setHorizontalGroup(
            errPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errPanelLayout.createSequentialGroup()
                .addGroup(errPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(errPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(errLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(errPanelLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(prev_err_button)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        errPanelLayout.setVerticalGroup(
            errPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(errLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prev_err_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        mainPanel.add(errPanel, "errPanel");

        home_book_button.setText("Book Cab");

        add_home_button.setText("Add Money");

        jLabel1.setText("User");

        username_label.setEditable(false);

        jLabel2.setText("Wallet");

        wallet_status_label.setEditable(false);

        home_err_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_err_label.setText("MoneyProblems");
        home_err_label.setVisible(false);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(home_err_label, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(homePanelLayout.createSequentialGroup()
                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(username_label)
                                    .addComponent(wallet_status_label, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, homePanelLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_home_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(home_book_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wallet_status_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(home_err_label)
                .addGap(18, 18, 18)
                .addComponent(home_book_button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add_home_button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        mainPanel.add(homePanel, "homePanel");

        jLabel3.setText("Balance");

        jTextField1.setEditable(false);

        jLabel5.setText("Money to add");

        jTextField2.setText("0");

        jLabel6.setText("Password");

        jButton1.setText("Add Money");

        jButton2.setText("Home");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jPasswordField1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel1, "card7");

        jMenu1.setText("File");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        jMenuItem1.setText("Home");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        sign_out_menuitem.setText("Sign Out");
        sign_out_menuitem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_out_menuitemMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sign_out_menuitemMousePressed(evt);
            }
        });
        jMenu1.add(sign_out_menuitem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExistingUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExistingUserButtonMouseClicked
        callSignInPanel();
//        CardLayout cards=(CardLayout)mainPanel.getLayout();
//        cards.show(mainPanel, "signinPanel");
    }//GEN-LAST:event_ExistingUserButtonMouseClicked

    private void NewUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserButtonMouseClicked
        callRegisterPanel();
//        CardLayout cards=(CardLayout)mainPanel.getLayout();
//        cards.show(mainPanel, "registerPanel");
    }//GEN-LAST:event_NewUserButtonMouseClicked

    private void sign_out_menuitemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_out_menuitemMouseClicked
//        
    }//GEN-LAST:event_sign_out_menuitemMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void sign_out_menuitemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_out_menuitemMousePressed
        callInitFrame();
//        System.out.println("clicked");
//        CardLayout cards=(CardLayout)mainPanel.getLayout();
//        err_reg_label.setVisible(false);
//        err_signin_label.setVisible(false);
//        cards.show(mainPanel, "initPanel");
    }//GEN-LAST:event_sign_out_menuitemMousePressed

    private void reset_reg_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_reg_buttonMouseClicked
        name_text.setText("");
        email_text.setText("");
        pass_reg_field.setText("");
        retypepass_reg_field.setText("");
    }//GEN-LAST:event_reset_reg_buttonMouseClicked

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        user_field.setText("");
        pass_field.setText("");
    }//GEN-LAST:event_resetMouseClicked

    private void signInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInMouseClicked
        String str=user_field.getText();
//        System.out.println("Clickedddddd");
//        callHomePanel();
//        System.out.println(str);
        if(!str.equals("Shreyam"))
        {
            err_signin_label.setText("Wrong user");
            err_signin_label.setVisible(true);
//            CardLayout cards=(CardLayout)mainPanel.getLayout();
//            errLabel.setText("Hiii !Shreyam");
//            prev="signinPanel";
//            cards.show(mainPanel, "errPanel");
        }
        else
        {
            callHomePanel("Welcome!!!!");            
        }
    }//GEN-LAST:event_signInMouseClicked

    private void prev_err_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prev_err_buttonMouseClicked
        CardLayout cards=(CardLayout)mainPanel.getLayout();
        cards.show(mainPanel, prev);
    }//GEN-LAST:event_prev_err_buttonMouseClicked

    private void reg_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_buttonMouseEntered

    
    private void reg_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_buttonMouseClicked

        if(!isRegValid())
        {
            err_reg_label.setText("Errorrrrr registering");
            err_reg_label.setVisible(true);            
        }
        else
        {
//            err_reg_label.setVisible(true);
//            err_reg_label.setText("Success Registering. Redirecting to Home...");
//            System.out.println("reg_button_clicked");
//            try{Thread.sleep(10000);}catch(Exception e){}
            
            callHomePanel("Registered You. Welcome!!!!");
        }
    }//GEN-LAST:event_reg_buttonMouseClicked

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        //if(User!=NULL)
        callHomePanel();
    }//GEN-LAST:event_jMenuItem1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExistingUserButton;
    private javax.swing.JButton NewUserButton;
    private javax.swing.JButton add_home_button;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField email_text;
    private javax.swing.JLabel errLabel;
    private javax.swing.JPanel errPanel;
    private javax.swing.JLabel err_reg_label;
    private javax.swing.JLabel err_signin_label;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton home_book_button;
    private javax.swing.JLabel home_err_label;
    private javax.swing.JPanel initPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_text;
    private javax.swing.JPasswordField pass_field;
    private javax.swing.JLabel pass_label;
    private javax.swing.JPasswordField pass_reg_field;
    private javax.swing.JLabel pass_reg_label;
    private javax.swing.JButton prev_err_button;
    private javax.swing.JButton reg_button;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JButton reset;
    private javax.swing.JButton reset_reg_button;
    private javax.swing.JPasswordField retypepass_reg_field;
    private javax.swing.JButton signIn;
    private javax.swing.JMenuItem sign_out_menuitem;
    private javax.swing.JPanel signinPanel;
    private javax.swing.JTextField user_field;
    private javax.swing.JLabel user_label;
    private javax.swing.JTextField username_label;
    private javax.swing.JTextField wallet_status_label;
    // End of variables declaration//GEN-END:variables
}
